install: skip

script: echo "Build!"

addons:
  ssh_known_hosts: ssh.chrisaiello.ca:7174

before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent  -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r -e 'ssh -p 7174' --delete-after --quiet $TRAVIS_BUILD_DIR chris@ssh.chrisaiello.ca:/home/chris/travis
  on:
    branch: main
